name: Aula de GCS (PUC CAMPINAS)

on: push

defaults:
  run:
    shell: bash
    # working-directory: 

jobs:
 primeiro:
    runs-on: ubuntu-latest
    steps:
       - name: Mostrar rodando
         run: echo "teste"
       - name: Event
         run: echo "${{github.event_name}} foi disparado"
    
 segundo:
   runs-on: windows-latest
   name: Segundo
   steps:
      - name: Criando variáveis
        env:
          VAR1: Isto é
          VAR2: Github Actions
        run: echo $VAR1 $VAR2
        
 terceiro:
    runs-on: ubuntu-latest
    steps:
      - run: | 
         echo "${{ github.event_name }} foi disparado"
         echo " No ${{runner.os}} "
    
